#!/bin/bash

# ============================================
# Exam Schedule Module - Quick Setup Guide
# ============================================
# This script provides commands to set up the Exam Schedule CRUD module

echo "🚀 Exam Schedule Module - Setup Instructions"
echo "============================================="
echo ""

# Step 1: Database Setup
echo "📊 STEP 1: Database Setup"
echo "------------------------"
echo "Run the migration to create the exam_schedules table:"
echo ""
echo "mysql -u root -p your_database < src/migrations/002_create_exam_schedules.sql"
echo ""
echo "OR paste this SQL in your MySQL client:"
echo ""
echo "Source file: src/migrations/002_create_exam_schedules.sql"
echo ""
echo "Verify the table was created:"
echo "mysql -u root -p your_database -e 'DESC exam_schedules;'"
echo ""
echo "---"
echo ""

# Step 2: Server Restart
echo "🔄 STEP 2: Restart the Server"
echo "----------------------------"
echo "The server.js file has been updated with the new routes."
echo "Restart your server:"
echo ""
echo "npm run dev"
echo "OR"
echo "node server.js"
echo ""
echo "You should see the server running on http://localhost:4001"
echo ""
echo "---"
echo ""

# Step 3: Verify Installation
echo "✅ STEP 3: Verify Installation"
echo "-----------------------------"
echo "Test the API endpoints:"
echo ""
echo "1. Access Swagger Documentation:"
echo "   http://localhost:4001/swagger"
echo ""
echo "2. Test with cURL (get JWT token first):"
echo ""
echo "   # Create an exam schedule"
echo "   curl -X POST http://localhost:4001/exam-schedules \\"
echo "     -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{"
echo "       \"exam_title\": \"Test Exam\","
echo "       \"start_datetime\": \"2026-07-15T10:00:00Z\","
echo "       \"end_datetime\": \"2026-07-15T12:00:00Z\","
echo "       \"exam_status\": \"Active\","
echo "       \"exam_category\": \"Abacus\","
echo "       \"exam_type\": \"Mock\""
echo "     }'"
echo ""
echo "   # Get all exam schedules"
echo "   curl -X GET \"http://localhost:4001/exam-schedules?page=1&limit=10\" \\"
echo "     -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "---"
echo ""

# Step 4: File Structure
echo "📁 STEP 4: File Structure"
echo "------------------------"
echo "The following files have been created/updated:"
echo ""
echo "✅ Backend/src/models/examSchedule.model.js"
echo "   └─ Database operations using mysql2/promise"
echo ""
echo "✅ Backend/src/services/examSchedule.service.js"
echo "   └─ Business logic, validation, CSV conversion"
echo ""
echo "✅ Backend/src/controllers/examSchedule.controller.js"
echo "   └─ HTTP request handlers (CRUD operations)"
echo ""
echo "✅ Backend/src/routes/examSchedule.routes.js"
echo "   └─ API route definitions with JWT middleware"
echo ""
echo "✅ Backend/src/docs/examSchedule.swagger.yaml"
echo "   └─ Swagger/OpenAPI documentation"
echo ""
echo "✅ Backend/src/migrations/002_create_exam_schedules.sql"
echo "   └─ Database schema with indexes"
echo ""
echo "✅ Backend/server.js (UPDATED)"
echo "   └─ Added new routes import and registration"
echo ""
echo "---"
echo ""

# Step 5: API Endpoints
echo "🔗 STEP 5: Available API Endpoints"
echo "---------------------------------"
echo ""
echo "POST   /exam-schedules                    - Create exam schedule"
echo "GET    /exam-schedules                    - Get all with pagination, search, filter, sort"
echo "GET    /exam-schedules/:id                - Get single exam schedule"
echo "PUT    /exam-schedules/:id                - Update exam schedule"
echo "DELETE /exam-schedules/:id                - Delete exam schedule"
echo "GET    /exam-schedules/export             - Export to JSON/CSV"
echo ""
echo "---"
echo ""

# Step 6: Features
echo "✨ STEP 6: Features Implemented"
echo "------------------------------"
echo ""
echo "✅ Complete CRUD operations"
echo "✅ JWT authentication (all endpoints protected)"
echo "✅ User-level data isolation (created_by)"
echo "✅ Pagination (page, limit)"
echo "✅ Search by exam_title"
echo "✅ Filter by exam_status, exam_category, exam_type"
echo "✅ Sort by created_at (DESC)"
echo "✅ CSV/JSON export"
echo "✅ Comprehensive validation"
echo "✅ Standard JSON response format"
echo "✅ Proper HTTP status codes (201, 200, 400, 404, 401, 500)"
echo "✅ Comments for every function"
echo "✅ Full Swagger documentation"
echo "✅ Database indexes for performance"
echo "✅ JSON columns support (exam_level, exam_set, exam_state, exam_district, exam_institute)"
echo ""
echo "---"
echo ""

# Step 7: Documentation
echo "📚 STEP 7: Documentation"
echo "-----------------------"
echo ""
echo "Complete documentation available in:"
echo "Backend/src/docs/EXAM_SCHEDULE_MODULE.md"
echo ""
echo "Includes:"
echo "  - API endpoint documentation"
echo "  - Request/response examples"
echo "  - cURL examples"
echo "  - Validation rules"
echo "  - Query parameters"
echo "  - Common issues & solutions"
echo "  - Performance considerations"
echo ""
echo "---"
echo ""

# Step 8: Testing
echo "🧪 STEP 8: Quick Testing"
echo "-----------------------"
echo ""
echo "1. Get your JWT token from /users/login or relevant auth endpoint"
echo ""
echo "2. Test CREATE:"
echo "   curl -X POST http://localhost:4001/exam-schedules \\"
echo "     -H 'Authorization: Bearer TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"exam_title\": \"Math Exam\", \"start_datetime\": \"2026-07-15T10:00:00Z\", \"end_datetime\": \"2026-07-15T12:00:00Z\", \"exam_status\": \"Active\", \"exam_category\": \"Abacus\", \"exam_type\": \"Mock\"}'"
echo ""
echo "3. Test READ:"
echo "   curl -X GET 'http://localhost:4001/exam-schedules?page=1' \\"
echo "     -H 'Authorization: Bearer TOKEN'"
echo ""
echo "4. Test UPDATE (replace 1 with actual ID):"
echo "   curl -X PUT http://localhost:4001/exam-schedules/1 \\"
echo "     -H 'Authorization: Bearer TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"exam_title\": \"Updated Title\"}'"
echo ""
echo "5. Test DELETE (replace 1 with actual ID):"
echo "   curl -X DELETE http://localhost:4001/exam-schedules/1 \\"
echo "     -H 'Authorization: Bearer TOKEN'"
echo ""
echo "---"
echo ""

# Step 9: Troubleshooting
echo "🔧 STEP 9: Troubleshooting"
echo "------------------------"
echo ""
echo "Issue: 'Exam Schedule not found'"
echo "  → User can only access their own records"
echo "  → Check that created_by matches your user ID"
echo ""
echo "Issue: Validation errors"
echo "  → Ensure all required fields are provided"
echo "  → Check enum values (Active/Inactive, Abacus/Vedic, Mock/Main Exam)"
echo "  → Verify end_datetime > start_datetime"
echo ""
echo "Issue: JWT token error"
echo "  → Authenticate first to get a valid token"
echo "  → Include 'Authorization: Bearer TOKEN' header"
echo ""
echo "Issue: Database connection error"
echo "  → Run migration first: 002_create_exam_schedules.sql"
echo "  → Check database credentials in .env"
echo "  → Verify database exists and is running"
echo ""
echo "---"
echo ""

echo "✅ Setup Complete!"
echo ""
echo "Next Steps:"
echo "1. Run the migration SQL"
echo "2. Restart the server"
echo "3. Test with cURL or Postman"
echo "4. Visit Swagger docs at http://localhost:4001/swagger"
echo ""
echo "For detailed documentation, see: Backend/src/docs/EXAM_SCHEDULE_MODULE.md"
echo ""
